version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9 
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running database migrations"
      - ls -lrt 
      - python3 gym_tracker/manage.py migrate
      - echo "Running Pylint"
      - pylint $CODEBUILD_SRC_DIR/*.py || echo "Pylint failed, continuing build..."
      - echo $CODEBUILD_SRC_DIR/*.py
  build:
    commands:
      - echo "Running tests"
      - pwd
      - python3 gym_tracker/manage.py test
  post_build:
    commands:
      - echo "Collecting static files"
      - python3 gym_tracker/manage.py collectstatic --noinput

artifacts:
  files:
    - '**/*' 
  discard-paths: no
