version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Adjust to your desired Python version
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running database migrations"
      - cd gym_tracker
      - python3 manage.py migrate
  build:
    commands:
      - echo "Running tests"
      - cd gym_tracker
      - python3 manage.py test
  post_build:
    commands:
      - echo "Collecting static files"
      - cd gym_tracker
      - python3 manage.py collectstatic --noinput

artifacts:
  files:
    - '**/*'  # Adjust depending on which files need to be included in artifacts
  discard-paths: no
