version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - python -m venv myenv
      - source myenv/bin/activate	
      - pip install -r requirements.txt
      - pip install boto3 
  build:
    commands:
      - echo Running Django pre-build steps...
      - python gym_tracker/manage.py check
  build:
    commands:
      - echo Building the Django application...
      - python gym_tracker/manage.py collectstatic --noinput
      - python gym_tracker/manage.py migrate
      - echo Application build complete.
  post_build:
    commands:
      - echo "Creating staticfiles directory"
      - mkdir -p gym_tracker/staticfiles  # Ensure the directory exists
      - echo "Collecting static files"
      - python3 gym_tracker/manage.py collectstatic --noinput

artifacts:
  files:
    - application.zip

