version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Adjust to your desired Python version
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running database migrations"
      - ls -lrt  # Verify the files in the source directory
      - python3 gym_tracker/manage.py migrate
      - echo "Running Pylint on gym_tracker directory"
      - pylint gym_tracker/*.py || echo "Pylint failed for gym_tracker, continuing build..."
  build:
    commands:
      - echo "Running tests"
      - pwd
      - python3 gym_tracker/manage.py test
  post_build:
    commands:
      - echo "Collecting static files"
      - python3 gym_tracker/manage.py collectstatic --noinput

artifacts:
  files:
    - '**/*'  # Adjust depending on which files need to be included in artifacts
  discard-paths: no
