version: 0.1

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Running database migrations"
      - python manage.py migrate
  build:
    commands:
      - echo "Running tests"
      - python manage.py test
  post_build:
    commands:
      - echo "Collecting static files"
      - python manage.py collectstatic --noinput

artifacts:
  files:
    - '**/*'
  discard-paths: no
