# Generated by Django 5.1.3 on 2024-11-11 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_goal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calorie_goal', models.PositiveIntegerField(blank=True, null=True)),
                ('workout_goal', models.PositiveIntegerField(blank=True, help_text='Number of workouts per week', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
